trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  Dotfuscator_License: '4824F7302305F68C9DE0B3EE2602AC63'  # Your Dotfuscator license key

steps:
- task: NuGetToolInstaller@1

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      curl -sSL https://dot.net/v1/dotnet-install.sh | bash
      echo "##vso[task.prependpath]/Library/Frameworks/Mono.framework/Versions/Current/bin"

# Install Dotfuscator NuGet Package
- task: NuGetCommand@2
  inputs:
    command: 'custom'
    arguments: 'install PreEmptive.Protection.Dotfuscator.Pro -OutputDirectory $(Agent.TempDirectory) -PreRelease -x -Source https://pkgs.dev.azure.com/nirajagrawal886/PRE622/_packaging/DotfuscatorFeed/nuget/v3/index.json'

# Restore the solution packages
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
  env:
    NUGET_RESTORE_MSBUILD_ARGS: '/p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)/PreEmptive.Protection.Dotfuscator.Pro/tools/msbuilddir/modern"'

# Log Dotfuscator installation location for debugging
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Dotfuscator installed at: $(Agent.TempDirectory)/PreEmptive.Protection.Dotfuscator.Pro/tools"
      ls -l $(Agent.TempDirectory)/PreEmptive.Protection.Dotfuscator.Pro/tools

# List files to verify the correct path
- script: |
    echo "Listing files in $(Build.SourcesDirectory)"
    ls -R $(Build.SourcesDirectory)
  displayName: 'List Files'

# Build Xamarin iOS project with Dotfuscator MSBuild Arguments
- task: XamarinIOS@1
  inputs:
    projectFile: './SimpleBlog/SimpleBlog.iOS/SimpleBlog.iOS.csproj'  # Ensure the correct iOS project is being built
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:DotfuscatorMSBuildDir="$(Agent.TempDirectory)/PreEmptive.Protection.Dotfuscator.Pro/tools/msbuilddir/modern" /p:DotfuscatorLicense="4824F7302305F68C9DE0B3EE2602AC63"'
    signingConfiguration: 'Auto'

# Publish build artifacts to the pipeline
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Artifacts'
    publishLocation: 'pipeline'
